### PR TITLE
Make code bundling-friendly and reduce code size a lot

### PR DESCRIPTION
**Pull request by addaleax**
Reduce the data file size from 411k to 2.8k and use plain JS files
so that the package is easier to bundle.

### CODE REVIEW

**Comment by reklatsmasters** [comment]
Good job, @addaleax! Could you remove `package-lock.json` changes from PR? I didn't find a way how to do that.

**Comment by reklatsmasters** [comment]
Sorry for slow answer, i'm on vacation.

**Comment by addaleax** [comment]
@reklatsmasters Sure, done, and thanks for the actually pretty fast response!

**Comment by addaleax** [comment]
@reklatsmasters Gentle ping :)

**Comment by addaleax** [comment]
@reklatsmasters Sorry to be annoying, but do you think you could publish another release of this library? :)

**Comment by kibertoad** [comment]
@reklatsmasters Any updates on the new version release?..

**Comment by vince1995** [comment]
@reklatsmasters when are you planning to do a version release?

**Comment by puschkin** [comment]
@reklatsmasters Hi, I would also be really interested in a new version!

**Comment by joewestcott** [comment]
Could we get a new version on NPM, this is a great PR!

**Comment by kahluagenie** [comment]
would love to see a publish of this!

**Pull request merged**
